- Y!J-SRD
- Y!J-MBS/1.0
- Yahoo! Slurp
- Yahoo! DE Slurp
- Googlebot-Mobile/
- Googlebot/
- adsence-Google
- msnbot
- bingbot/
- Hatena
- MicroAd/
- Baidu
- MJ12bo
- Steeler
- YodaoBot
- OutfoxBot
- Pockey
- psbot
- Yeti/
- Websi
- Wget/
- NaverBot
- BecomeBot
- heritr
- DotBot
- Twiceler
- ichiro
- archive.org_bot
- YandexBot/
- ICC-Crawler
- SiteBot/
- TurnitinBot/
- Purebot/